consumption <- read.csv("C:/Users/Erick/Downloads/household_power_consumption.txt", sep=";", na.strings="?",stringsAsFactors = FALSE)
consumption$DateTime<-strptime(paste(consumption$Date,consumption$Time),'%d/%m/%Y %H:%M:%S')
studied_consumption<-subset(consumption,DateTime>=strptime('2007-02-01','%Y-%m-%d') & DateTime<strptime('2007-02-03','%Y-%m-%d'))
png(file="plot3.png", width=480, height=480)
plot(studied_consumption$DateTime,studied_consumption$Sub_metering_1,type="l",col="black",xlab="",ylab="Energy sub metering")
lines(studied_consumption$DateTime,studied_consumption$Sub_metering_2,type="l",col="red")
lines(studied_consumption$DateTime,studied_consumption$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty="solid")
dev.off()